# -*- coding: utf-8 -*-
"""MST_Python_Week2_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SaGZShosXfytqPwledrDMmbHgcSJS7dG
"""

# 1. Write an interactive Python Program to implement following “Guess Game”
# i. Think of a number between 1 and 10 and store it in a variable called "secretNumber".
# ii. Ask the user to enter a number between 1 and 10 and store it in a variable called "guess".
# iii. Use control statements (if-else) to check if the guess is correct, higher, or lower than the secret number.
# iv. Display appropriate messages to the user based on their guess: 
 #•If the guess is correct, display "Congratulations! You guessed the number correctly!" 
 #• If the guess is higher than the secret number, display "Too high! Try again." 
 #• If the guess is lower than the secret number, display "Too low! Try again."
# v. Allow the user to keep guessing until they guess the correct number.
import random 
secretNumber = random. randint(1, 10) 
guess = None 
while guess != secretNumber: 
  guess = int(input("Enter a number between 1 and 10: ")) 
  if guess == secretNumber: 
    print("Congratulations! You guessed the number correctly!")
  elif guess> secretNumber:
     print("Too high! Try again.")
  elif guess< secretNumber:
     print("Too low! Try again.")

#2. Write a program to find and print the Factorial of this number. The Factorial of a positive
#integer N refers to the product of all number in the range from 1 to N.

num =int(input("Enter the number to find the factorial:"))
factorial = 1
if num < 0:
   print("The number is a negative number")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

#3 • Roy wants to change his profile picture on Facebook. Now Facebook has some
#restriction over the dimension of picture that we can upload.
#Minimum dimension of the picture can be L x L, where L is the length of the side
#of square. Now Roy has N photos of various dimensions.
#Dimension of a photo is denoted as W x H
#where W - width of the photo and H - Height of the photo
#• When any photo is uploaded following events may occur:
#[1] If any of the width or height is less than L, user is prompted to upload another
#one. Print "UPLOAD ANOTHER" in this case.
#[2] If width and height, both are large enough and
#(a) if the photo is already square then it is accepted. Print "ACCEPTED" in this
#case.
#(b) else user is prompted to crop it. Print "CROP IT" in this case.
#Given L, N, W and H as input, write a program to print appropriate text as output.

photo_len=int(input("Enter the length of the photo"))
num_photo=int(input("Enter the number of photos to upload"))
while num_photo>0:
  photo_width=int(input("Enter the width of the photo"))
  photo_height=int(input("Enter the Height of the photo")) 
  if  photo_width<photo_len or photo_height<photo_len:   
    print("UPLOAD ANOTHER")
  elif photo_width>=photo_len and  photo_height>=photo_len and photo_width==photo_height:
     print("ACCEPTED")
  elif photo_width>=photo_len and  photo_height>=photo_len and photo_width!=photo_height:   
    print("CROP IT")    
  num_photo= num_photo-1